// http://rosalind.info/problems/subs/

package main
import "fmt"
func main() {
    var a string = "ACACTACCGTACACTACACACTACAAACACTACCAAACACTACACACTACGGTATACACTACACATATAACACTACACACTACACACTACACACTACACACTACGACACTACACACTACACACTACTACACTACTAACACTACAACACTACCGTGAATCGTGACAAGACACTACCATGACACTACAACACTACACACTACCGACACTACCTCCACAACACTACGCCACTAACACTACACACTACACACTACACACTACGACACTACGTACACTACACACTACCCACACTACACACTACACACTACGTTCTTGTTCACACTACGACACTACACACTACGTGCATCTATTACACTACCACACTACCACACACTACACACTACGTCTACACTACACACTACTACACTACACACTACACACTACTACACTACGAACACTACCCTACACTACGTCAAACACTACTCACACTACCGACACTACTGCGAAGTCACACTACTCGGGTGAGTACACTACACACTACAATCACACTACGAACACTACAGAACACTACCCCACACTACCCGACACTACGCACACTACACACTACGACACTACACACTACGACACTACGTGATACCTTGACACACTACGCACAAACACTACACACTACACACTACTTACACTACACACTACACACTACACCCACACTACACACTACCACACTACTACACTACCAAACACTACAGCCACACTACACACTACGAGAAACACTACCTTCGGGCACACTACCAGTCGTACACTACCGAAGAACACTACGGTAA"
    var b string = "ACACTACAC"
    var pozice []int
    for i := 0; i <= len(a)-len(b); i++ {
      if a[i:i+len(b)] == b {
        pozice = append(pozice, i+1)
      }
    }
    fmt.Println(pozice)
}
